[book]
authors = ['Ryan Lambert', 'RustProof Labs']
language = "en"
multilingual = false
src = "src"
title = "PgOSM Flex Faker"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/rustprooflabs/pgosm-flex-faker"
git-repository-icon = "fa-github"
